// Code generated by github.com/swaggest/go-code-builder, DO NOT EDIT.

package swagger

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
)

// SwaggerSchema structure is generated from "#".
//
// A JSON Schema for Swagger 2.0 API.
type SwaggerSchema struct {
	Info                *Info                                              `json:"info,omitempty"`                // General information about the API.
	Host                string                                             `json:"host,omitempty"`                // The host (name or ip) of the API. Example: 'swagger.io'
	BasePath            string                                             `json:"basePath,omitempty"`            // The base path to the API. Example: '/api'.
	Schemes             []SchemesListItems                                 `json:"schemes,omitempty"`             // The transfer protocol of the API.
	Consumes            []string                                           `json:"consumes,omitempty"`            // A list of MIME types accepted by the API.
	Produces            []string                                           `json:"produces,omitempty"`            // A list of MIME types the API can produce.
	Paths               *Paths                                             `json:"paths,omitempty"`               // Relative paths to the individual endpoints. They must be relative to the 'basePath'.
	Definitions         map[string]Schema                                  `json:"definitions,omitempty"`         // One or more JSON objects describing the schemas being consumed and produced by the API.
	Parameters          map[string]Parameter                               `json:"parameters,omitempty"`          // One or more JSON representations for parameters
	Responses           map[string]Response                                `json:"responses,omitempty"`           // One or more JSON representations for parameters
	Security            []map[string][]string                              `json:"security,omitempty"`
	SecurityDefinitions map[string]SecurityDefinitionsAdditionalProperties `json:"securityDefinitions,omitempty"`
	Tags                []Tag                                              `json:"tags,omitempty"`
	ExternalDocs        *ExternalDocs                                      `json:"externalDocs,omitempty"`        // information about external documentation
	MapOfAnything       map[string]interface{}                             `json:"-"`                             // Key must match pattern: ^x-
}

type marshalSwaggerSchema SwaggerSchema

var ignoreKeysSwaggerSchema = []string{
	"info",
	"host",
	"basePath",
	"schemes",
	"consumes",
	"produces",
	"paths",
	"definitions",
	"parameters",
	"responses",
	"security",
	"securityDefinitions",
	"tags",
	"externalDocs",
	"swagger",
}

// UnmarshalJSON decodes JSON.
func (i *SwaggerSchema) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalSwaggerSchema(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["swagger"]; !ok || string(v) != `"2.0"` {
		return fmt.Errorf(`bad or missing const value for "swagger" ("2.0" expected, %s received)`, v)
	}

	delete(m, "swagger")

	for _, key := range ignoreKeysSwaggerSchema {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = SwaggerSchema(ii)

	return nil
}

var (
	// constSwaggerSchema is unconditionally added to JSON.
	constSwaggerSchema = json.RawMessage(`{"swagger":"2.0"}`)
)

// MarshalJSON encodes JSON.
func (i SwaggerSchema) MarshalJSON() ([]byte, error) {
	return marshalUnion(constSwaggerSchema, marshalSwaggerSchema(i), i.MapOfAnything)
}

// Info structure is generated from "#/definitions/info".
//
// General information about the API.
type Info struct {
	Title          string                 `json:"title,omitempty"`          // A unique and precise title of the API.
	Version        string                 `json:"version,omitempty"`        // A semantic version number of the API.
	Description    string                 `json:"description,omitempty"`    // A longer description of the API. Should be different from the title.  GitHub Flavored Markdown is allowed.
	TermsOfService string                 `json:"termsOfService,omitempty"` // The terms of service for the API.
	Contact        *Contact               `json:"contact,omitempty"`        // Contact information for the owners of the API.
	License        *License               `json:"license,omitempty"`
	MapOfAnything  map[string]interface{} `json:"-"`                        // Key must match pattern: ^x-
}

type marshalInfo Info

var ignoreKeysInfo = []string{
	"title",
	"version",
	"description",
	"termsOfService",
	"contact",
	"license",
}

// UnmarshalJSON decodes JSON.
func (i *Info) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalInfo(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysInfo {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Info(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i Info) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalInfo(i), i.MapOfAnything)
}

// Contact structure is generated from "#/definitions/contact".
//
// Contact information for the owners of the API.
type Contact struct {
	Name          string                 `json:"name,omitempty"`  // The identifying name of the contact person/organization.
	URL           string                 `json:"url,omitempty"`   // The URL pointing to the contact information.
	Email         string                 `json:"email,omitempty"` // The email address of the contact person/organization.
	MapOfAnything map[string]interface{} `json:"-"`               // Key must match pattern: ^x-
}

type marshalContact Contact

var ignoreKeysContact = []string{
	"name",
	"url",
	"email",
}

// UnmarshalJSON decodes JSON.
func (i *Contact) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalContact(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysContact {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Contact(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i Contact) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalContact(i), i.MapOfAnything)
}

// License structure is generated from "#/definitions/license".
type License struct {
	Name          string                 `json:"name,omitempty"` // The name of the license type. It's encouraged to use an OSI compatible license.
	URL           string                 `json:"url,omitempty"`  // The URL pointing to the license.
	MapOfAnything map[string]interface{} `json:"-"`              // Key must match pattern: ^x-
}

type marshalLicense License

var ignoreKeysLicense = []string{
	"name",
	"url",
}

// UnmarshalJSON decodes JSON.
func (i *License) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalLicense(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysLicense {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = License(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i License) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalLicense(i), i.MapOfAnything)
}

// Paths structure is generated from "#/definitions/paths".
//
// Relative paths to the individual endpoints. They must be relative to the 'basePath'.
type Paths struct {
	MapOfAnything       map[string]interface{} `json:"-"` // Key must match pattern: ^x-
	MapOfPathItemValues map[string]PathItem    `json:"-"` // Key must match pattern: ^/
}

// UnmarshalJSON decodes JSON.
func (i *Paths) UnmarshalJSON(data []byte) error {
	var err error

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if i.MapOfAnything == nil {
					i.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				i.MapOfAnything[key] = val
			}

			if regex.MatchString(key) {
				matched = true

				if i.MapOfPathItemValues == nil {
					i.MapOfPathItemValues = make(map[string]PathItem, 1)
				}

				var val PathItem

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				i.MapOfPathItemValues[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i Paths) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.MapOfAnything, i.MapOfPathItemValues)
}

// PathItem structure is generated from "#/definitions/pathItem".
type PathItem struct {
	Ref           string                 `json:"$ref,omitempty"`
	Get           *Operation             `json:"get,omitempty"`
	Put           *Operation             `json:"put,omitempty"`
	Post          *Operation             `json:"post,omitempty"`
	Delete        *Operation             `json:"delete,omitempty"`
	Options       *Operation             `json:"options,omitempty"`
	Head          *Operation             `json:"head,omitempty"`
	Patch         *Operation             `json:"patch,omitempty"`
	Parameters    []ParametersListItems  `json:"parameters,omitempty"` // The parameters needed to send a valid API call.
	MapOfAnything map[string]interface{} `json:"-"`                    // Key must match pattern: ^x-
}

type marshalPathItem PathItem

var ignoreKeysPathItem = []string{
	"$ref",
	"get",
	"put",
	"post",
	"delete",
	"options",
	"head",
	"patch",
	"parameters",
}

// UnmarshalJSON decodes JSON.
func (i *PathItem) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalPathItem(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysPathItem {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = PathItem(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i PathItem) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalPathItem(i), i.MapOfAnything)
}

// Operation structure is generated from "#/definitions/operation".
type Operation struct {
	Tags          []string               `json:"tags,omitempty"`
	Summary       string                 `json:"summary,omitempty"`      // A brief summary of the operation.
	Description   string                 `json:"description,omitempty"`  // A longer description of the operation, GitHub Flavored Markdown is allowed.
	ExternalDocs  *ExternalDocs          `json:"externalDocs,omitempty"` // information about external documentation
	ID            string                 `json:"operationId,omitempty"`  // A unique identifier of the operation.
	Produces      []string               `json:"produces,omitempty"`     // A list of MIME types the API can produce.
	Consumes      []string               `json:"consumes,omitempty"`     // A list of MIME types the API can consume.
	Parameters    []ParametersListItems  `json:"parameters,omitempty"`   // The parameters needed to send a valid API call.
	Responses     *Responses             `json:"responses,omitempty"`    // Response objects names can either be any valid HTTP status code or 'default'.
	Schemes       []SchemesListItems     `json:"schemes,omitempty"`      // The transfer protocol of the API.
	Deprecated    bool                   `json:"deprecated,omitempty"`
	Security      []map[string][]string  `json:"security,omitempty"`
	MapOfAnything map[string]interface{} `json:"-"`                      // Key must match pattern: ^x-
}

type marshalOperation Operation

var ignoreKeysOperation = []string{
	"tags",
	"summary",
	"description",
	"externalDocs",
	"operationId",
	"produces",
	"consumes",
	"parameters",
	"responses",
	"schemes",
	"deprecated",
	"security",
}

// UnmarshalJSON decodes JSON.
func (i *Operation) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalOperation(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysOperation {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Operation(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i Operation) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalOperation(i), i.MapOfAnything)
}

// ExternalDocs structure is generated from "#/definitions/externalDocs".
//
// information about external documentation.
type ExternalDocs struct {
	Description   string                 `json:"description,omitempty"`
	URL           string                 `json:"url,omitempty"`
	MapOfAnything map[string]interface{} `json:"-"`                     // Key must match pattern: ^x-
}

type marshalExternalDocs ExternalDocs

var ignoreKeysExternalDocs = []string{
	"description",
	"url",
}

// UnmarshalJSON decodes JSON.
func (i *ExternalDocs) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalExternalDocs(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysExternalDocs {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = ExternalDocs(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i ExternalDocs) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalExternalDocs(i), i.MapOfAnything)
}

// BodyParameter structure is generated from "#/definitions/bodyParameter".
type BodyParameter struct {
	Description   string                 `json:"description,omitempty"` // A brief description of the parameter. This could contain examples of use.  GitHub Flavored Markdown is allowed.
	Name          string                 `json:"name,omitempty"`        // The name of the parameter.
	Required      bool                   `json:"required,omitempty"`    // Determines whether or not this parameter is required or optional.
	Schema        *Schema                `json:"schema,omitempty"`      // A deterministic version of a JSON Schema object.
	MapOfAnything map[string]interface{} `json:"-"`                     // Key must match pattern: ^x-
}

type marshalBodyParameter BodyParameter

var ignoreKeysBodyParameter = []string{
	"description",
	"name",
	"required",
	"schema",
	"in",
}

// UnmarshalJSON decodes JSON.
func (i *BodyParameter) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalBodyParameter(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["in"]; !ok || string(v) != `"body"` {
		return fmt.Errorf(`bad or missing const value for "in" ("body" expected, %s received)`, v)
	}

	delete(m, "in")

	for _, key := range ignoreKeysBodyParameter {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = BodyParameter(ii)

	return nil
}

var (
	// constBodyParameter is unconditionally added to JSON.
	constBodyParameter = json.RawMessage(`{"in":"body"}`)
)

// MarshalJSON encodes JSON.
func (i BodyParameter) MarshalJSON() ([]byte, error) {
	return marshalUnion(constBodyParameter, marshalBodyParameter(i), i.MapOfAnything)
}

// Schema structure is generated from "#/definitions/schema".
//
// A deterministic version of a JSON Schema object.
type Schema struct {
	Ref                  string                                        `json:"$ref,omitempty"`
	Format               string                                        `json:"format,omitempty"`
	Title                string                                        `json:"title,omitempty"`
	Description          string                                        `json:"description,omitempty"`
	Default              *interface{}                                  `json:"default,omitempty"`
	MultipleOf           float64                                       `json:"multipleOf,omitempty"`
	Maximum              float64                                       `json:"maximum,omitempty"`
	ExclusiveMaximum     bool                                          `json:"exclusiveMaximum,omitempty"`
	Minimum              float64                                       `json:"minimum,omitempty"`
	ExclusiveMinimum     bool                                          `json:"exclusiveMinimum,omitempty"`
	MaxLength            int64                                         `json:"maxLength,omitempty"`
	MinLength            int64                                         `json:"minLength,omitempty"`
	Pattern              string                                        `json:"pattern,omitempty"`
	MaxItems             int64                                         `json:"maxItems,omitempty"`
	MinItems             int64                                         `json:"minItems,omitempty"`
	UniqueItems          bool                                          `json:"uniqueItems,omitempty"`
	MaxProperties        int64                                         `json:"maxProperties,omitempty"`
	MinProperties        int64                                         `json:"minProperties,omitempty"`
	Required             []string                                      `json:"required,omitempty"`
	Enum                 []interface{}                                 `json:"enum,omitempty"`
	MapOfAnything        map[string]interface{}                        `json:"-"`                              // Key must match pattern: ^x-
	AdditionalProperties *SchemaAdditionalProperties                   `json:"additionalProperties,omitempty"`
	Type                 *HTTPJSONSchemaOrgDraft04SchemaPropertiesType `json:"type,omitempty"`
	Items                *SchemaItems                                  `json:"items,omitempty"`
	AllOf                []Schema                                      `json:"allOf,omitempty"`
	Properties           map[string]Schema                             `json:"properties,omitempty"`
	Discriminator        string                                        `json:"discriminator,omitempty"`
	ReadOnly             bool                                          `json:"readOnly,omitempty"`
	XML                  *XML                                          `json:"xml,omitempty"`
	ExternalDocs         *ExternalDocs                                 `json:"externalDocs,omitempty"`         // information about external documentation
	Example              *interface{}                                  `json:"example,omitempty"`
}

type marshalSchema Schema

var ignoreKeysSchema = []string{
	"$ref",
	"format",
	"title",
	"description",
	"default",
	"multipleOf",
	"maximum",
	"exclusiveMaximum",
	"minimum",
	"exclusiveMinimum",
	"maxLength",
	"minLength",
	"pattern",
	"maxItems",
	"minItems",
	"uniqueItems",
	"maxProperties",
	"minProperties",
	"required",
	"enum",
	"additionalProperties",
	"type",
	"items",
	"allOf",
	"properties",
	"discriminator",
	"readOnly",
	"xml",
	"externalDocs",
	"example",
}

// UnmarshalJSON decodes JSON.
func (i *Schema) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalSchema(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if ii.Default == nil {
		if _, ok := m["default"]; ok {
			var v interface{}
			ii.Default = &v
		}
	}

	if ii.Example == nil {
		if _, ok := m["example"]; ok {
			var v interface{}
			ii.Example = &v
		}
	}

	for _, key := range ignoreKeysSchema {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Schema(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i Schema) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalSchema(i), i.MapOfAnything)
}

// SchemaAdditionalProperties structure is generated from "#/definitions/schema->additionalProperties".
type SchemaAdditionalProperties struct {
	Schema *Schema `json:"-"`
	Bool   *bool   `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (i *SchemaAdditionalProperties) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &i.Schema)
	if err != nil {
		i.Schema = nil
	}

	err = json.Unmarshal(data, &i.Bool)
	if err != nil {
		i.Bool = nil
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i SchemaAdditionalProperties) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.Schema, i.Bool)
}

// HTTPJSONSchemaOrgDraft04SchemaPropertiesType structure is generated from "http://json-schema.org/draft-04/schema#/properties/type".
type HTTPJSONSchemaOrgDraft04SchemaPropertiesType struct {
	SimpleTypes              *SimpleTypes  `json:"-"`
	SliceOfSimpleTypesValues []SimpleTypes `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (i *HTTPJSONSchemaOrgDraft04SchemaPropertiesType) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &i.SimpleTypes)
	if err != nil {
		i.SimpleTypes = nil
	}

	err = json.Unmarshal(data, &i.SliceOfSimpleTypesValues)
	if err != nil {
		i.SliceOfSimpleTypesValues = nil
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i HTTPJSONSchemaOrgDraft04SchemaPropertiesType) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.SimpleTypes, i.SliceOfSimpleTypesValues)
}

// SchemaItems structure is generated from "#/definitions/schema->items".
type SchemaItems struct {
	Schema              *Schema  `json:"-"`
	SliceOfSchemaValues []Schema `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (i *SchemaItems) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &i.Schema)
	if err != nil {
		i.Schema = nil
	}

	err = json.Unmarshal(data, &i.SliceOfSchemaValues)
	if err != nil {
		i.SliceOfSchemaValues = nil
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i SchemaItems) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.Schema, i.SliceOfSchemaValues)
}

// XML structure is generated from "#/definitions/xml".
type XML struct {
	Name          string                 `json:"name,omitempty"`
	Namespace     string                 `json:"namespace,omitempty"`
	Prefix        string                 `json:"prefix,omitempty"`
	Attribute     bool                   `json:"attribute,omitempty"`
	Wrapped       bool                   `json:"wrapped,omitempty"`
	MapOfAnything map[string]interface{} `json:"-"`                   // Key must match pattern: ^x-
}

type marshalXML XML

var ignoreKeysXML = []string{
	"name",
	"namespace",
	"prefix",
	"attribute",
	"wrapped",
}

// UnmarshalJSON decodes JSON.
func (i *XML) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalXML(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysXML {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = XML(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i XML) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalXML(i), i.MapOfAnything)
}

// HeaderParameterSubSchema structure is generated from "#/definitions/headerParameterSubSchema".
type HeaderParameterSubSchema struct {
	Required         bool                         `json:"required,omitempty"`         // Determines whether or not this parameter is required or optional.
	Description      string                       `json:"description,omitempty"`      // A brief description of the parameter. This could contain examples of use.  GitHub Flavored Markdown is allowed.
	Name             string                       `json:"name,omitempty"`             // The name of the parameter.
	Type             HeaderParameterSubSchemaType `json:"type,omitempty"`
	Format           string                       `json:"format,omitempty"`
	Items            *PrimitivesItems             `json:"items,omitempty"`
	CollectionFormat CollectionFormat             `json:"collectionFormat,omitempty"`
	Default          *interface{}                 `json:"default,omitempty"`
	Maximum          float64                      `json:"maximum,omitempty"`
	ExclusiveMaximum bool                         `json:"exclusiveMaximum,omitempty"`
	Minimum          float64                      `json:"minimum,omitempty"`
	ExclusiveMinimum bool                         `json:"exclusiveMinimum,omitempty"`
	MaxLength        int64                        `json:"maxLength,omitempty"`
	MinLength        int64                        `json:"minLength,omitempty"`
	Pattern          string                       `json:"pattern,omitempty"`
	MaxItems         int64                        `json:"maxItems,omitempty"`
	MinItems         int64                        `json:"minItems,omitempty"`
	UniqueItems      bool                         `json:"uniqueItems,omitempty"`
	Enum             []interface{}                `json:"enum,omitempty"`
	MultipleOf       float64                      `json:"multipleOf,omitempty"`
	MapOfAnything    map[string]interface{}       `json:"-"`                          // Key must match pattern: ^x-
}

type marshalHeaderParameterSubSchema HeaderParameterSubSchema

var ignoreKeysHeaderParameterSubSchema = []string{
	"required",
	"description",
	"name",
	"type",
	"format",
	"items",
	"collectionFormat",
	"default",
	"maximum",
	"exclusiveMaximum",
	"minimum",
	"exclusiveMinimum",
	"maxLength",
	"minLength",
	"pattern",
	"maxItems",
	"minItems",
	"uniqueItems",
	"enum",
	"multipleOf",
	"in",
}

// UnmarshalJSON decodes JSON.
func (i *HeaderParameterSubSchema) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalHeaderParameterSubSchema(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["in"]; !ok || string(v) != `"header"` {
		return fmt.Errorf(`bad or missing const value for "in" ("header" expected, %s received)`, v)
	}

	delete(m, "in")

	if ii.Default == nil {
		if _, ok := m["default"]; ok {
			var v interface{}
			ii.Default = &v
		}
	}

	for _, key := range ignoreKeysHeaderParameterSubSchema {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = HeaderParameterSubSchema(ii)

	return nil
}

var (
	// constHeaderParameterSubSchema is unconditionally added to JSON.
	constHeaderParameterSubSchema = json.RawMessage(`{"in":"header"}`)
)

// MarshalJSON encodes JSON.
func (i HeaderParameterSubSchema) MarshalJSON() ([]byte, error) {
	return marshalUnion(constHeaderParameterSubSchema, marshalHeaderParameterSubSchema(i), i.MapOfAnything)
}

// PrimitivesItems structure is generated from "#/definitions/primitivesItems".
type PrimitivesItems struct {
	Type             PrimitivesItemsType    `json:"type,omitempty"`
	Format           string                 `json:"format,omitempty"`
	MapOfAnything    map[string]interface{} `json:"-"`                          // Key must match pattern: ^x-
	Items            *PrimitivesItems       `json:"items,omitempty"`
	CollectionFormat CollectionFormat       `json:"collectionFormat,omitempty"`
	Default          *interface{}           `json:"default,omitempty"`
	Maximum          float64                `json:"maximum,omitempty"`
	ExclusiveMaximum bool                   `json:"exclusiveMaximum,omitempty"`
	Minimum          float64                `json:"minimum,omitempty"`
	ExclusiveMinimum bool                   `json:"exclusiveMinimum,omitempty"`
	MaxLength        int64                  `json:"maxLength,omitempty"`
	MinLength        int64                  `json:"minLength,omitempty"`
	Pattern          string                 `json:"pattern,omitempty"`
	MaxItems         int64                  `json:"maxItems,omitempty"`
	MinItems         int64                  `json:"minItems,omitempty"`
	UniqueItems      bool                   `json:"uniqueItems,omitempty"`
	Enum             []interface{}          `json:"enum,omitempty"`
	MultipleOf       float64                `json:"multipleOf,omitempty"`
}

type marshalPrimitivesItems PrimitivesItems

var ignoreKeysPrimitivesItems = []string{
	"type",
	"format",
	"items",
	"collectionFormat",
	"default",
	"maximum",
	"exclusiveMaximum",
	"minimum",
	"exclusiveMinimum",
	"maxLength",
	"minLength",
	"pattern",
	"maxItems",
	"minItems",
	"uniqueItems",
	"enum",
	"multipleOf",
}

// UnmarshalJSON decodes JSON.
func (i *PrimitivesItems) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalPrimitivesItems(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if ii.Default == nil {
		if _, ok := m["default"]; ok {
			var v interface{}
			ii.Default = &v
		}
	}

	for _, key := range ignoreKeysPrimitivesItems {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = PrimitivesItems(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i PrimitivesItems) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalPrimitivesItems(i), i.MapOfAnything)
}

// FormDataParameterSubSchema structure is generated from "#/definitions/formDataParameterSubSchema".
type FormDataParameterSubSchema struct {
	Required         bool                           `json:"required,omitempty"`         // Determines whether or not this parameter is required or optional.
	Description      string                         `json:"description,omitempty"`      // A brief description of the parameter. This could contain examples of use.  GitHub Flavored Markdown is allowed.
	Name             string                         `json:"name,omitempty"`             // The name of the parameter.
	AllowEmptyValue  bool                           `json:"allowEmptyValue,omitempty"`  // allows sending a parameter by name only or with an empty value.
	Type             FormDataParameterSubSchemaType `json:"type,omitempty"`
	Format           string                         `json:"format,omitempty"`
	Items            *PrimitivesItems               `json:"items,omitempty"`
	CollectionFormat CollectionFormatWithMulti      `json:"collectionFormat,omitempty"`
	Default          *interface{}                   `json:"default,omitempty"`
	Maximum          float64                        `json:"maximum,omitempty"`
	ExclusiveMaximum bool                           `json:"exclusiveMaximum,omitempty"`
	Minimum          float64                        `json:"minimum,omitempty"`
	ExclusiveMinimum bool                           `json:"exclusiveMinimum,omitempty"`
	MaxLength        int64                          `json:"maxLength,omitempty"`
	MinLength        int64                          `json:"minLength,omitempty"`
	Pattern          string                         `json:"pattern,omitempty"`
	MaxItems         int64                          `json:"maxItems,omitempty"`
	MinItems         int64                          `json:"minItems,omitempty"`
	UniqueItems      bool                           `json:"uniqueItems,omitempty"`
	Enum             []interface{}                  `json:"enum,omitempty"`
	MultipleOf       float64                        `json:"multipleOf,omitempty"`
	MapOfAnything    map[string]interface{}         `json:"-"`                          // Key must match pattern: ^x-
}

type marshalFormDataParameterSubSchema FormDataParameterSubSchema

var ignoreKeysFormDataParameterSubSchema = []string{
	"required",
	"description",
	"name",
	"allowEmptyValue",
	"type",
	"format",
	"items",
	"collectionFormat",
	"default",
	"maximum",
	"exclusiveMaximum",
	"minimum",
	"exclusiveMinimum",
	"maxLength",
	"minLength",
	"pattern",
	"maxItems",
	"minItems",
	"uniqueItems",
	"enum",
	"multipleOf",
	"in",
}

// UnmarshalJSON decodes JSON.
func (i *FormDataParameterSubSchema) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalFormDataParameterSubSchema(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["in"]; !ok || string(v) != `"formData"` {
		return fmt.Errorf(`bad or missing const value for "in" ("formData" expected, %s received)`, v)
	}

	delete(m, "in")

	if ii.Default == nil {
		if _, ok := m["default"]; ok {
			var v interface{}
			ii.Default = &v
		}
	}

	for _, key := range ignoreKeysFormDataParameterSubSchema {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = FormDataParameterSubSchema(ii)

	return nil
}

var (
	// constFormDataParameterSubSchema is unconditionally added to JSON.
	constFormDataParameterSubSchema = json.RawMessage(`{"in":"formData"}`)
)

// MarshalJSON encodes JSON.
func (i FormDataParameterSubSchema) MarshalJSON() ([]byte, error) {
	return marshalUnion(constFormDataParameterSubSchema, marshalFormDataParameterSubSchema(i), i.MapOfAnything)
}

// QueryParameterSubSchema structure is generated from "#/definitions/queryParameterSubSchema".
type QueryParameterSubSchema struct {
	Required         bool                        `json:"required,omitempty"`         // Determines whether or not this parameter is required or optional.
	Description      string                      `json:"description,omitempty"`      // A brief description of the parameter. This could contain examples of use.  GitHub Flavored Markdown is allowed.
	Name             string                      `json:"name,omitempty"`             // The name of the parameter.
	AllowEmptyValue  bool                        `json:"allowEmptyValue,omitempty"`  // allows sending a parameter by name only or with an empty value.
	Type             QueryParameterSubSchemaType `json:"type,omitempty"`
	Format           string                      `json:"format,omitempty"`
	Items            *PrimitivesItems            `json:"items,omitempty"`
	CollectionFormat CollectionFormatWithMulti   `json:"collectionFormat,omitempty"`
	Default          *interface{}                `json:"default,omitempty"`
	Maximum          float64                     `json:"maximum,omitempty"`
	ExclusiveMaximum bool                        `json:"exclusiveMaximum,omitempty"`
	Minimum          float64                     `json:"minimum,omitempty"`
	ExclusiveMinimum bool                        `json:"exclusiveMinimum,omitempty"`
	MaxLength        int64                       `json:"maxLength,omitempty"`
	MinLength        int64                       `json:"minLength,omitempty"`
	Pattern          string                      `json:"pattern,omitempty"`
	MaxItems         int64                       `json:"maxItems,omitempty"`
	MinItems         int64                       `json:"minItems,omitempty"`
	UniqueItems      bool                        `json:"uniqueItems,omitempty"`
	Enum             []interface{}               `json:"enum,omitempty"`
	MultipleOf       float64                     `json:"multipleOf,omitempty"`
	MapOfAnything    map[string]interface{}      `json:"-"`                          // Key must match pattern: ^x-
}

type marshalQueryParameterSubSchema QueryParameterSubSchema

var ignoreKeysQueryParameterSubSchema = []string{
	"required",
	"description",
	"name",
	"allowEmptyValue",
	"type",
	"format",
	"items",
	"collectionFormat",
	"default",
	"maximum",
	"exclusiveMaximum",
	"minimum",
	"exclusiveMinimum",
	"maxLength",
	"minLength",
	"pattern",
	"maxItems",
	"minItems",
	"uniqueItems",
	"enum",
	"multipleOf",
	"in",
}

// UnmarshalJSON decodes JSON.
func (i *QueryParameterSubSchema) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalQueryParameterSubSchema(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["in"]; !ok || string(v) != `"query"` {
		return fmt.Errorf(`bad or missing const value for "in" ("query" expected, %s received)`, v)
	}

	delete(m, "in")

	if ii.Default == nil {
		if _, ok := m["default"]; ok {
			var v interface{}
			ii.Default = &v
		}
	}

	for _, key := range ignoreKeysQueryParameterSubSchema {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = QueryParameterSubSchema(ii)

	return nil
}

var (
	// constQueryParameterSubSchema is unconditionally added to JSON.
	constQueryParameterSubSchema = json.RawMessage(`{"in":"query"}`)
)

// MarshalJSON encodes JSON.
func (i QueryParameterSubSchema) MarshalJSON() ([]byte, error) {
	return marshalUnion(constQueryParameterSubSchema, marshalQueryParameterSubSchema(i), i.MapOfAnything)
}

// PathParameterSubSchema structure is generated from "#/definitions/pathParameterSubSchema".
type PathParameterSubSchema struct {
	Description      string                     `json:"description,omitempty"`      // A brief description of the parameter. This could contain examples of use.  GitHub Flavored Markdown is allowed.
	Name             string                     `json:"name,omitempty"`             // The name of the parameter.
	Type             PathParameterSubSchemaType `json:"type,omitempty"`
	Format           string                     `json:"format,omitempty"`
	Items            *PrimitivesItems           `json:"items,omitempty"`
	CollectionFormat CollectionFormat           `json:"collectionFormat,omitempty"`
	Default          *interface{}               `json:"default,omitempty"`
	Maximum          float64                    `json:"maximum,omitempty"`
	ExclusiveMaximum bool                       `json:"exclusiveMaximum,omitempty"`
	Minimum          float64                    `json:"minimum,omitempty"`
	ExclusiveMinimum bool                       `json:"exclusiveMinimum,omitempty"`
	MaxLength        int64                      `json:"maxLength,omitempty"`
	MinLength        int64                      `json:"minLength,omitempty"`
	Pattern          string                     `json:"pattern,omitempty"`
	MaxItems         int64                      `json:"maxItems,omitempty"`
	MinItems         int64                      `json:"minItems,omitempty"`
	UniqueItems      bool                       `json:"uniqueItems,omitempty"`
	Enum             []interface{}              `json:"enum,omitempty"`
	MultipleOf       float64                    `json:"multipleOf,omitempty"`
	MapOfAnything    map[string]interface{}     `json:"-"`                          // Key must match pattern: ^x-
}

type marshalPathParameterSubSchema PathParameterSubSchema

var ignoreKeysPathParameterSubSchema = []string{
	"description",
	"name",
	"type",
	"format",
	"items",
	"collectionFormat",
	"default",
	"maximum",
	"exclusiveMaximum",
	"minimum",
	"exclusiveMinimum",
	"maxLength",
	"minLength",
	"pattern",
	"maxItems",
	"minItems",
	"uniqueItems",
	"enum",
	"multipleOf",
	"required",
	"in",
}

// UnmarshalJSON decodes JSON.
func (i *PathParameterSubSchema) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalPathParameterSubSchema(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["required"]; !ok || string(v) != "true" {
		return fmt.Errorf(`bad or missing const value for "required" (true expected, %s received)`, v)
	}

	delete(m, "required")

	if v, ok := m["in"]; !ok || string(v) != `"path"` {
		return fmt.Errorf(`bad or missing const value for "in" ("path" expected, %s received)`, v)
	}

	delete(m, "in")

	if ii.Default == nil {
		if _, ok := m["default"]; ok {
			var v interface{}
			ii.Default = &v
		}
	}

	for _, key := range ignoreKeysPathParameterSubSchema {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = PathParameterSubSchema(ii)

	return nil
}

var (
	// constPathParameterSubSchema is unconditionally added to JSON.
	constPathParameterSubSchema = json.RawMessage(`{"required":true,"in":"path"}`)
)

// MarshalJSON encodes JSON.
func (i PathParameterSubSchema) MarshalJSON() ([]byte, error) {
	return marshalUnion(constPathParameterSubSchema, marshalPathParameterSubSchema(i), i.MapOfAnything)
}

// NonBodyParameter structure is generated from "#/definitions/nonBodyParameter".
type NonBodyParameter struct {
	HeaderParameterSubSchema   *HeaderParameterSubSchema   `json:"-"`
	FormDataParameterSubSchema *FormDataParameterSubSchema `json:"-"`
	QueryParameterSubSchema    *QueryParameterSubSchema    `json:"-"`
	PathParameterSubSchema     *PathParameterSubSchema     `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (i *NonBodyParameter) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &i.HeaderParameterSubSchema)
	if err != nil {
		i.HeaderParameterSubSchema = nil
	}

	err = json.Unmarshal(data, &i.FormDataParameterSubSchema)
	if err != nil {
		i.FormDataParameterSubSchema = nil
	}

	err = json.Unmarshal(data, &i.QueryParameterSubSchema)
	if err != nil {
		i.QueryParameterSubSchema = nil
	}

	err = json.Unmarshal(data, &i.PathParameterSubSchema)
	if err != nil {
		i.PathParameterSubSchema = nil
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i NonBodyParameter) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.HeaderParameterSubSchema, i.FormDataParameterSubSchema, i.QueryParameterSubSchema, i.PathParameterSubSchema)
}

// Parameter structure is generated from "#/definitions/parameter".
type Parameter struct {
	BodyParameter    *BodyParameter    `json:"-"`
	NonBodyParameter *NonBodyParameter `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (i *Parameter) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &i.BodyParameter)
	if err != nil {
		i.BodyParameter = nil
	}

	err = json.Unmarshal(data, &i.NonBodyParameter)
	if err != nil {
		i.NonBodyParameter = nil
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i Parameter) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.BodyParameter, i.NonBodyParameter)
}

// JSONReference structure is generated from "#/definitions/jsonReference".
type JSONReference struct {
	Ref string `json:"$ref,omitempty"`
}

// ParametersListItems structure is generated from "#/definitions/parametersList->items".
type ParametersListItems struct {
	Parameter     *Parameter     `json:"-"`
	JSONReference *JSONReference `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (i *ParametersListItems) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &i.Parameter)
	if err != nil {
		i.Parameter = nil
	}

	err = json.Unmarshal(data, &i.JSONReference)
	if err != nil {
		i.JSONReference = nil
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i ParametersListItems) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.Parameter, i.JSONReference)
}

// Response structure is generated from "#/definitions/response".
type Response struct {
	Description   string                 `json:"description,omitempty"`
	Schema        *ResponseSchema        `json:"schema,omitempty"`
	Headers       map[string]Header      `json:"headers,omitempty"`
	Examples      map[string]interface{} `json:"examples,omitempty"`
	MapOfAnything map[string]interface{} `json:"-"`                     // Key must match pattern: ^x-
}

type marshalResponse Response

var ignoreKeysResponse = []string{
	"description",
	"schema",
	"headers",
	"examples",
}

// UnmarshalJSON decodes JSON.
func (i *Response) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalResponse(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysResponse {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Response(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i Response) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalResponse(i), i.MapOfAnything)
}

// FileSchema structure is generated from "#/definitions/fileSchema".
//
// A deterministic version of a JSON Schema object.
type FileSchema struct {
	Format        string                 `json:"format,omitempty"`
	Title         string                 `json:"title,omitempty"`
	Description   string                 `json:"description,omitempty"`
	Default       *interface{}           `json:"default,omitempty"`
	Required      []string               `json:"required,omitempty"`
	ReadOnly      bool                   `json:"readOnly,omitempty"`
	ExternalDocs  *ExternalDocs          `json:"externalDocs,omitempty"` // information about external documentation
	Example       *interface{}           `json:"example,omitempty"`
	MapOfAnything map[string]interface{} `json:"-"`                      // Key must match pattern: ^x-
}

type marshalFileSchema FileSchema

var ignoreKeysFileSchema = []string{
	"format",
	"title",
	"description",
	"default",
	"required",
	"readOnly",
	"externalDocs",
	"example",
	"type",
}

// UnmarshalJSON decodes JSON.
func (i *FileSchema) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalFileSchema(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["type"]; !ok || string(v) != `"file"` {
		return fmt.Errorf(`bad or missing const value for "type" ("file" expected, %s received)`, v)
	}

	delete(m, "type")

	if ii.Default == nil {
		if _, ok := m["default"]; ok {
			var v interface{}
			ii.Default = &v
		}
	}

	if ii.Example == nil {
		if _, ok := m["example"]; ok {
			var v interface{}
			ii.Example = &v
		}
	}

	for _, key := range ignoreKeysFileSchema {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = FileSchema(ii)

	return nil
}

var (
	// constFileSchema is unconditionally added to JSON.
	constFileSchema = json.RawMessage(`{"type":"file"}`)
)

// MarshalJSON encodes JSON.
func (i FileSchema) MarshalJSON() ([]byte, error) {
	return marshalUnion(constFileSchema, marshalFileSchema(i), i.MapOfAnything)
}

// ResponseSchema structure is generated from "#/definitions/response->schema".
type ResponseSchema struct {
	Schema     *Schema     `json:"-"`
	FileSchema *FileSchema `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (i *ResponseSchema) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &i.Schema)
	if err != nil {
		i.Schema = nil
	}

	err = json.Unmarshal(data, &i.FileSchema)
	if err != nil {
		i.FileSchema = nil
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i ResponseSchema) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.Schema, i.FileSchema)
}

// Header structure is generated from "#/definitions/header".
type Header struct {
	Type             HeaderType             `json:"type,omitempty"`
	Format           string                 `json:"format,omitempty"`
	Items            *PrimitivesItems       `json:"items,omitempty"`
	CollectionFormat CollectionFormat       `json:"collectionFormat,omitempty"`
	Default          *interface{}           `json:"default,omitempty"`
	Maximum          float64                `json:"maximum,omitempty"`
	ExclusiveMaximum bool                   `json:"exclusiveMaximum,omitempty"`
	Minimum          float64                `json:"minimum,omitempty"`
	ExclusiveMinimum bool                   `json:"exclusiveMinimum,omitempty"`
	MaxLength        int64                  `json:"maxLength,omitempty"`
	MinLength        int64                  `json:"minLength,omitempty"`
	Pattern          string                 `json:"pattern,omitempty"`
	MaxItems         int64                  `json:"maxItems,omitempty"`
	MinItems         int64                  `json:"minItems,omitempty"`
	UniqueItems      bool                   `json:"uniqueItems,omitempty"`
	Enum             []interface{}          `json:"enum,omitempty"`
	MultipleOf       float64                `json:"multipleOf,omitempty"`
	Description      string                 `json:"description,omitempty"`
	MapOfAnything    map[string]interface{} `json:"-"`                          // Key must match pattern: ^x-
}

type marshalHeader Header

var ignoreKeysHeader = []string{
	"type",
	"format",
	"items",
	"collectionFormat",
	"default",
	"maximum",
	"exclusiveMaximum",
	"minimum",
	"exclusiveMinimum",
	"maxLength",
	"minLength",
	"pattern",
	"maxItems",
	"minItems",
	"uniqueItems",
	"enum",
	"multipleOf",
	"description",
}

// UnmarshalJSON decodes JSON.
func (i *Header) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalHeader(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if ii.Default == nil {
		if _, ok := m["default"]; ok {
			var v interface{}
			ii.Default = &v
		}
	}

	for _, key := range ignoreKeysHeader {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Header(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i Header) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalHeader(i), i.MapOfAnything)
}

// ResponseValue structure is generated from "#/definitions/responseValue".
type ResponseValue struct {
	Response      *Response      `json:"-"`
	JSONReference *JSONReference `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (i *ResponseValue) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &i.Response)
	if err != nil {
		i.Response = nil
	}

	err = json.Unmarshal(data, &i.JSONReference)
	if err != nil {
		i.JSONReference = nil
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i ResponseValue) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.Response, i.JSONReference)
}

// Responses structure is generated from "#/definitions/responses".
//
// Response objects names can either be any valid HTTP status code or 'default'.
type Responses struct {
	MapOfResponseValueValues map[string]ResponseValue `json:"-"` // Key must match pattern: ^([0-9]{3})$|^(default)$
	MapOfAnything            map[string]interface{}   `json:"-"` // Key must match pattern: ^x-
}

// UnmarshalJSON decodes JSON.
func (i *Responses) UnmarshalJSON(data []byte) error {
	var err error

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for key, rawValue := range m {
		matched := false

			if regex093Default.MatchString(key) {
				matched = true

				if i.MapOfResponseValueValues == nil {
					i.MapOfResponseValueValues = make(map[string]ResponseValue, 1)
				}

				var val ResponseValue

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				i.MapOfResponseValueValues[key] = val
			}

			if regexX.MatchString(key) {
				matched = true

				if i.MapOfAnything == nil {
					i.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				i.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i Responses) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.MapOfResponseValueValues, i.MapOfAnything)
}

// BasicAuthenticationSecurity structure is generated from "#/definitions/basicAuthenticationSecurity".
type BasicAuthenticationSecurity struct {
	Description   string                 `json:"description,omitempty"`
	MapOfAnything map[string]interface{} `json:"-"`                     // Key must match pattern: ^x-
}

type marshalBasicAuthenticationSecurity BasicAuthenticationSecurity

var ignoreKeysBasicAuthenticationSecurity = []string{
	"description",
	"type",
}

// UnmarshalJSON decodes JSON.
func (i *BasicAuthenticationSecurity) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalBasicAuthenticationSecurity(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["type"]; !ok || string(v) != `"basic"` {
		return fmt.Errorf(`bad or missing const value for "type" ("basic" expected, %s received)`, v)
	}

	delete(m, "type")

	for _, key := range ignoreKeysBasicAuthenticationSecurity {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = BasicAuthenticationSecurity(ii)

	return nil
}

var (
	// constBasicAuthenticationSecurity is unconditionally added to JSON.
	constBasicAuthenticationSecurity = json.RawMessage(`{"type":"basic"}`)
)

// MarshalJSON encodes JSON.
func (i BasicAuthenticationSecurity) MarshalJSON() ([]byte, error) {
	return marshalUnion(constBasicAuthenticationSecurity, marshalBasicAuthenticationSecurity(i), i.MapOfAnything)
}

// APIKeySecurity structure is generated from "#/definitions/apiKeySecurity".
type APIKeySecurity struct {
	Name          string                 `json:"name,omitempty"`
	In            APIKeySecurityIn       `json:"in,omitempty"`
	Description   string                 `json:"description,omitempty"`
	MapOfAnything map[string]interface{} `json:"-"`                     // Key must match pattern: ^x-
}

type marshalAPIKeySecurity APIKeySecurity

var ignoreKeysAPIKeySecurity = []string{
	"name",
	"in",
	"description",
	"type",
}

// UnmarshalJSON decodes JSON.
func (i *APIKeySecurity) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalAPIKeySecurity(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["type"]; !ok || string(v) != `"apiKey"` {
		return fmt.Errorf(`bad or missing const value for "type" ("apiKey" expected, %s received)`, v)
	}

	delete(m, "type")

	for _, key := range ignoreKeysAPIKeySecurity {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = APIKeySecurity(ii)

	return nil
}

var (
	// constAPIKeySecurity is unconditionally added to JSON.
	constAPIKeySecurity = json.RawMessage(`{"type":"apiKey"}`)
)

// MarshalJSON encodes JSON.
func (i APIKeySecurity) MarshalJSON() ([]byte, error) {
	return marshalUnion(constAPIKeySecurity, marshalAPIKeySecurity(i), i.MapOfAnything)
}

// Oauth2ImplicitSecurity structure is generated from "#/definitions/oauth2ImplicitSecurity".
type Oauth2ImplicitSecurity struct {
	Scopes           map[string]string      `json:"scopes,omitempty"`
	AuthorizationURL string                 `json:"authorizationUrl,omitempty"`
	Description      string                 `json:"description,omitempty"`
	MapOfAnything    map[string]interface{} `json:"-"`                          // Key must match pattern: ^x-
}

type marshalOauth2ImplicitSecurity Oauth2ImplicitSecurity

var ignoreKeysOauth2ImplicitSecurity = []string{
	"scopes",
	"authorizationUrl",
	"description",
	"type",
	"flow",
}

// UnmarshalJSON decodes JSON.
func (i *Oauth2ImplicitSecurity) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalOauth2ImplicitSecurity(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["type"]; !ok || string(v) != `"oauth2"` {
		return fmt.Errorf(`bad or missing const value for "type" ("oauth2" expected, %s received)`, v)
	}

	delete(m, "type")

	if v, ok := m["flow"]; !ok || string(v) != `"implicit"` {
		return fmt.Errorf(`bad or missing const value for "flow" ("implicit" expected, %s received)`, v)
	}

	delete(m, "flow")

	for _, key := range ignoreKeysOauth2ImplicitSecurity {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Oauth2ImplicitSecurity(ii)

	return nil
}

var (
	// constOauth2ImplicitSecurity is unconditionally added to JSON.
	constOauth2ImplicitSecurity = json.RawMessage(`{"type":"oauth2","flow":"implicit"}`)
)

// MarshalJSON encodes JSON.
func (i Oauth2ImplicitSecurity) MarshalJSON() ([]byte, error) {
	return marshalUnion(constOauth2ImplicitSecurity, marshalOauth2ImplicitSecurity(i), i.MapOfAnything)
}

// Oauth2PasswordSecurity structure is generated from "#/definitions/oauth2PasswordSecurity".
type Oauth2PasswordSecurity struct {
	Scopes        map[string]string      `json:"scopes,omitempty"`
	TokenURL      string                 `json:"tokenUrl,omitempty"`
	Description   string                 `json:"description,omitempty"`
	MapOfAnything map[string]interface{} `json:"-"`                     // Key must match pattern: ^x-
}

type marshalOauth2PasswordSecurity Oauth2PasswordSecurity

var ignoreKeysOauth2PasswordSecurity = []string{
	"scopes",
	"tokenUrl",
	"description",
	"type",
	"flow",
}

// UnmarshalJSON decodes JSON.
func (i *Oauth2PasswordSecurity) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalOauth2PasswordSecurity(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["type"]; !ok || string(v) != `"oauth2"` {
		return fmt.Errorf(`bad or missing const value for "type" ("oauth2" expected, %s received)`, v)
	}

	delete(m, "type")

	if v, ok := m["flow"]; !ok || string(v) != `"password"` {
		return fmt.Errorf(`bad or missing const value for "flow" ("password" expected, %s received)`, v)
	}

	delete(m, "flow")

	for _, key := range ignoreKeysOauth2PasswordSecurity {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Oauth2PasswordSecurity(ii)

	return nil
}

var (
	// constOauth2PasswordSecurity is unconditionally added to JSON.
	constOauth2PasswordSecurity = json.RawMessage(`{"type":"oauth2","flow":"password"}`)
)

// MarshalJSON encodes JSON.
func (i Oauth2PasswordSecurity) MarshalJSON() ([]byte, error) {
	return marshalUnion(constOauth2PasswordSecurity, marshalOauth2PasswordSecurity(i), i.MapOfAnything)
}

// Oauth2ApplicationSecurity structure is generated from "#/definitions/oauth2ApplicationSecurity".
type Oauth2ApplicationSecurity struct {
	Scopes        map[string]string      `json:"scopes,omitempty"`
	TokenURL      string                 `json:"tokenUrl,omitempty"`
	Description   string                 `json:"description,omitempty"`
	MapOfAnything map[string]interface{} `json:"-"`                     // Key must match pattern: ^x-
}

type marshalOauth2ApplicationSecurity Oauth2ApplicationSecurity

var ignoreKeysOauth2ApplicationSecurity = []string{
	"scopes",
	"tokenUrl",
	"description",
	"type",
	"flow",
}

// UnmarshalJSON decodes JSON.
func (i *Oauth2ApplicationSecurity) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalOauth2ApplicationSecurity(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["type"]; !ok || string(v) != `"oauth2"` {
		return fmt.Errorf(`bad or missing const value for "type" ("oauth2" expected, %s received)`, v)
	}

	delete(m, "type")

	if v, ok := m["flow"]; !ok || string(v) != `"application"` {
		return fmt.Errorf(`bad or missing const value for "flow" ("application" expected, %s received)`, v)
	}

	delete(m, "flow")

	for _, key := range ignoreKeysOauth2ApplicationSecurity {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Oauth2ApplicationSecurity(ii)

	return nil
}

var (
	// constOauth2ApplicationSecurity is unconditionally added to JSON.
	constOauth2ApplicationSecurity = json.RawMessage(`{"type":"oauth2","flow":"application"}`)
)

// MarshalJSON encodes JSON.
func (i Oauth2ApplicationSecurity) MarshalJSON() ([]byte, error) {
	return marshalUnion(constOauth2ApplicationSecurity, marshalOauth2ApplicationSecurity(i), i.MapOfAnything)
}

// Oauth2AccessCodeSecurity structure is generated from "#/definitions/oauth2AccessCodeSecurity".
type Oauth2AccessCodeSecurity struct {
	Scopes           map[string]string      `json:"scopes,omitempty"`
	AuthorizationURL string                 `json:"authorizationUrl,omitempty"`
	TokenURL         string                 `json:"tokenUrl,omitempty"`
	Description      string                 `json:"description,omitempty"`
	MapOfAnything    map[string]interface{} `json:"-"`                          // Key must match pattern: ^x-
}

type marshalOauth2AccessCodeSecurity Oauth2AccessCodeSecurity

var ignoreKeysOauth2AccessCodeSecurity = []string{
	"scopes",
	"authorizationUrl",
	"tokenUrl",
	"description",
	"type",
	"flow",
}

// UnmarshalJSON decodes JSON.
func (i *Oauth2AccessCodeSecurity) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalOauth2AccessCodeSecurity(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	if v, ok := m["type"]; !ok || string(v) != `"oauth2"` {
		return fmt.Errorf(`bad or missing const value for "type" ("oauth2" expected, %s received)`, v)
	}

	delete(m, "type")

	if v, ok := m["flow"]; !ok || string(v) != `"accessCode"` {
		return fmt.Errorf(`bad or missing const value for "flow" ("accessCode" expected, %s received)`, v)
	}

	delete(m, "flow")

	for _, key := range ignoreKeysOauth2AccessCodeSecurity {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Oauth2AccessCodeSecurity(ii)

	return nil
}

var (
	// constOauth2AccessCodeSecurity is unconditionally added to JSON.
	constOauth2AccessCodeSecurity = json.RawMessage(`{"type":"oauth2","flow":"accessCode"}`)
)

// MarshalJSON encodes JSON.
func (i Oauth2AccessCodeSecurity) MarshalJSON() ([]byte, error) {
	return marshalUnion(constOauth2AccessCodeSecurity, marshalOauth2AccessCodeSecurity(i), i.MapOfAnything)
}

// SecurityDefinitionsAdditionalProperties structure is generated from "#/definitions/securityDefinitions->additionalProperties".
type SecurityDefinitionsAdditionalProperties struct {
	BasicAuthenticationSecurity *BasicAuthenticationSecurity `json:"-"`
	APIKeySecurity              *APIKeySecurity              `json:"-"`
	Oauth2ImplicitSecurity      *Oauth2ImplicitSecurity      `json:"-"`
	Oauth2PasswordSecurity      *Oauth2PasswordSecurity      `json:"-"`
	Oauth2ApplicationSecurity   *Oauth2ApplicationSecurity   `json:"-"`
	Oauth2AccessCodeSecurity    *Oauth2AccessCodeSecurity    `json:"-"`
}

// UnmarshalJSON decodes JSON.
func (i *SecurityDefinitionsAdditionalProperties) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &i.BasicAuthenticationSecurity)
	if err != nil {
		i.BasicAuthenticationSecurity = nil
	}

	err = json.Unmarshal(data, &i.APIKeySecurity)
	if err != nil {
		i.APIKeySecurity = nil
	}

	err = json.Unmarshal(data, &i.Oauth2ImplicitSecurity)
	if err != nil {
		i.Oauth2ImplicitSecurity = nil
	}

	err = json.Unmarshal(data, &i.Oauth2PasswordSecurity)
	if err != nil {
		i.Oauth2PasswordSecurity = nil
	}

	err = json.Unmarshal(data, &i.Oauth2ApplicationSecurity)
	if err != nil {
		i.Oauth2ApplicationSecurity = nil
	}

	err = json.Unmarshal(data, &i.Oauth2AccessCodeSecurity)
	if err != nil {
		i.Oauth2AccessCodeSecurity = nil
	}

	return nil
}

// MarshalJSON encodes JSON.
func (i SecurityDefinitionsAdditionalProperties) MarshalJSON() ([]byte, error) {
	return marshalUnion(i.BasicAuthenticationSecurity, i.APIKeySecurity, i.Oauth2ImplicitSecurity, i.Oauth2PasswordSecurity, i.Oauth2ApplicationSecurity, i.Oauth2AccessCodeSecurity)
}

// Tag structure is generated from "#/definitions/tag".
type Tag struct {
	Name          string                 `json:"name,omitempty"`
	Description   string                 `json:"description,omitempty"`
	ExternalDocs  *ExternalDocs          `json:"externalDocs,omitempty"` // information about external documentation
	MapOfAnything map[string]interface{} `json:"-"`                      // Key must match pattern: ^x-
}

type marshalTag Tag

var ignoreKeysTag = []string{
	"name",
	"description",
	"externalDocs",
}

// UnmarshalJSON decodes JSON.
func (i *Tag) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalTag(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysTag {
		delete(m, key)
	}

	for key, rawValue := range m {
		matched := false

			if regexX.MatchString(key) {
				matched = true

				if ii.MapOfAnything == nil {
					ii.MapOfAnything = make(map[string]interface{}, 1)
				}

				var val interface{}

				err = json.Unmarshal(rawValue, &val)
				if err != nil {
					return err
				}

				ii.MapOfAnything[key] = val
			}

		if matched {
			delete(m, key)
		}
	}

	*i = Tag(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i Tag) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalTag(i), i.MapOfAnything)
}

// SchemesListItems is an enum type.
type SchemesListItems string

// SchemesListItems values enumeration.
const (
	SchemesListItemsHTTP = SchemesListItems("http")
	SchemesListItemsHTTPS = SchemesListItems("https")
	SchemesListItemsWs = SchemesListItems("ws")
	SchemesListItemsWss = SchemesListItems("wss")
)

// MarshalJSON encodes JSON.
func (i SchemesListItems) MarshalJSON() ([]byte, error) {
	switch i {
	case SchemesListItemsHTTP:
	case SchemesListItemsHTTPS:
	case SchemesListItemsWs:
	case SchemesListItemsWss:

	default:
		return nil, fmt.Errorf("unexpected SchemesListItems value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *SchemesListItems) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := SchemesListItems(ii)

	switch v {
	case SchemesListItemsHTTP:
	case SchemesListItemsHTTPS:
	case SchemesListItemsWs:
	case SchemesListItemsWss:

	default:
		return fmt.Errorf("unexpected SchemesListItems value: %v", v)
	}

	*i = v

	return nil
}

// SimpleTypes is an enum type.
type SimpleTypes string

// SimpleTypes values enumeration.
const (
	SimpleTypesArray = SimpleTypes("array")
	SimpleTypesBoolean = SimpleTypes("boolean")
	SimpleTypesInteger = SimpleTypes("integer")
	SimpleTypesNull = SimpleTypes("null")
	SimpleTypesNumber = SimpleTypes("number")
	SimpleTypesObject = SimpleTypes("object")
	SimpleTypesString = SimpleTypes("string")
)

// MarshalJSON encodes JSON.
func (i SimpleTypes) MarshalJSON() ([]byte, error) {
	switch i {
	case SimpleTypesArray:
	case SimpleTypesBoolean:
	case SimpleTypesInteger:
	case SimpleTypesNull:
	case SimpleTypesNumber:
	case SimpleTypesObject:
	case SimpleTypesString:

	default:
		return nil, fmt.Errorf("unexpected SimpleTypes value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *SimpleTypes) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := SimpleTypes(ii)

	switch v {
	case SimpleTypesArray:
	case SimpleTypesBoolean:
	case SimpleTypesInteger:
	case SimpleTypesNull:
	case SimpleTypesNumber:
	case SimpleTypesObject:
	case SimpleTypesString:

	default:
		return fmt.Errorf("unexpected SimpleTypes value: %v", v)
	}

	*i = v

	return nil
}

// HeaderParameterSubSchemaType is an enum type.
type HeaderParameterSubSchemaType string

// HeaderParameterSubSchemaType values enumeration.
const (
	HeaderParameterSubSchemaTypeString = HeaderParameterSubSchemaType("string")
	HeaderParameterSubSchemaTypeNumber = HeaderParameterSubSchemaType("number")
	HeaderParameterSubSchemaTypeBoolean = HeaderParameterSubSchemaType("boolean")
	HeaderParameterSubSchemaTypeInteger = HeaderParameterSubSchemaType("integer")
	HeaderParameterSubSchemaTypeArray = HeaderParameterSubSchemaType("array")
)

// MarshalJSON encodes JSON.
func (i HeaderParameterSubSchemaType) MarshalJSON() ([]byte, error) {
	switch i {
	case HeaderParameterSubSchemaTypeString:
	case HeaderParameterSubSchemaTypeNumber:
	case HeaderParameterSubSchemaTypeBoolean:
	case HeaderParameterSubSchemaTypeInteger:
	case HeaderParameterSubSchemaTypeArray:

	default:
		return nil, fmt.Errorf("unexpected HeaderParameterSubSchemaType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *HeaderParameterSubSchemaType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := HeaderParameterSubSchemaType(ii)

	switch v {
	case HeaderParameterSubSchemaTypeString:
	case HeaderParameterSubSchemaTypeNumber:
	case HeaderParameterSubSchemaTypeBoolean:
	case HeaderParameterSubSchemaTypeInteger:
	case HeaderParameterSubSchemaTypeArray:

	default:
		return fmt.Errorf("unexpected HeaderParameterSubSchemaType value: %v", v)
	}

	*i = v

	return nil
}

// PrimitivesItemsType is an enum type.
type PrimitivesItemsType string

// PrimitivesItemsType values enumeration.
const (
	PrimitivesItemsTypeString = PrimitivesItemsType("string")
	PrimitivesItemsTypeNumber = PrimitivesItemsType("number")
	PrimitivesItemsTypeInteger = PrimitivesItemsType("integer")
	PrimitivesItemsTypeBoolean = PrimitivesItemsType("boolean")
	PrimitivesItemsTypeArray = PrimitivesItemsType("array")
)

// MarshalJSON encodes JSON.
func (i PrimitivesItemsType) MarshalJSON() ([]byte, error) {
	switch i {
	case PrimitivesItemsTypeString:
	case PrimitivesItemsTypeNumber:
	case PrimitivesItemsTypeInteger:
	case PrimitivesItemsTypeBoolean:
	case PrimitivesItemsTypeArray:

	default:
		return nil, fmt.Errorf("unexpected PrimitivesItemsType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *PrimitivesItemsType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := PrimitivesItemsType(ii)

	switch v {
	case PrimitivesItemsTypeString:
	case PrimitivesItemsTypeNumber:
	case PrimitivesItemsTypeInteger:
	case PrimitivesItemsTypeBoolean:
	case PrimitivesItemsTypeArray:

	default:
		return fmt.Errorf("unexpected PrimitivesItemsType value: %v", v)
	}

	*i = v

	return nil
}

// CollectionFormat is an enum type.
type CollectionFormat string

// CollectionFormat values enumeration.
const (
	CollectionFormatCsv = CollectionFormat("csv")
	CollectionFormatSsv = CollectionFormat("ssv")
	CollectionFormatTsv = CollectionFormat("tsv")
	CollectionFormatPipes = CollectionFormat("pipes")
)

// MarshalJSON encodes JSON.
func (i CollectionFormat) MarshalJSON() ([]byte, error) {
	switch i {
	case CollectionFormatCsv:
	case CollectionFormatSsv:
	case CollectionFormatTsv:
	case CollectionFormatPipes:

	default:
		return nil, fmt.Errorf("unexpected CollectionFormat value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *CollectionFormat) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := CollectionFormat(ii)

	switch v {
	case CollectionFormatCsv:
	case CollectionFormatSsv:
	case CollectionFormatTsv:
	case CollectionFormatPipes:

	default:
		return fmt.Errorf("unexpected CollectionFormat value: %v", v)
	}

	*i = v

	return nil
}

// FormDataParameterSubSchemaType is an enum type.
type FormDataParameterSubSchemaType string

// FormDataParameterSubSchemaType values enumeration.
const (
	FormDataParameterSubSchemaTypeString = FormDataParameterSubSchemaType("string")
	FormDataParameterSubSchemaTypeNumber = FormDataParameterSubSchemaType("number")
	FormDataParameterSubSchemaTypeBoolean = FormDataParameterSubSchemaType("boolean")
	FormDataParameterSubSchemaTypeInteger = FormDataParameterSubSchemaType("integer")
	FormDataParameterSubSchemaTypeArray = FormDataParameterSubSchemaType("array")
	FormDataParameterSubSchemaTypeFile = FormDataParameterSubSchemaType("file")
)

// MarshalJSON encodes JSON.
func (i FormDataParameterSubSchemaType) MarshalJSON() ([]byte, error) {
	switch i {
	case FormDataParameterSubSchemaTypeString:
	case FormDataParameterSubSchemaTypeNumber:
	case FormDataParameterSubSchemaTypeBoolean:
	case FormDataParameterSubSchemaTypeInteger:
	case FormDataParameterSubSchemaTypeArray:
	case FormDataParameterSubSchemaTypeFile:

	default:
		return nil, fmt.Errorf("unexpected FormDataParameterSubSchemaType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *FormDataParameterSubSchemaType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := FormDataParameterSubSchemaType(ii)

	switch v {
	case FormDataParameterSubSchemaTypeString:
	case FormDataParameterSubSchemaTypeNumber:
	case FormDataParameterSubSchemaTypeBoolean:
	case FormDataParameterSubSchemaTypeInteger:
	case FormDataParameterSubSchemaTypeArray:
	case FormDataParameterSubSchemaTypeFile:

	default:
		return fmt.Errorf("unexpected FormDataParameterSubSchemaType value: %v", v)
	}

	*i = v

	return nil
}

// CollectionFormatWithMulti is an enum type.
type CollectionFormatWithMulti string

// CollectionFormatWithMulti values enumeration.
const (
	CollectionFormatWithMultiCsv = CollectionFormatWithMulti("csv")
	CollectionFormatWithMultiSsv = CollectionFormatWithMulti("ssv")
	CollectionFormatWithMultiTsv = CollectionFormatWithMulti("tsv")
	CollectionFormatWithMultiPipes = CollectionFormatWithMulti("pipes")
	CollectionFormatWithMultiMulti = CollectionFormatWithMulti("multi")
)

// MarshalJSON encodes JSON.
func (i CollectionFormatWithMulti) MarshalJSON() ([]byte, error) {
	switch i {
	case CollectionFormatWithMultiCsv:
	case CollectionFormatWithMultiSsv:
	case CollectionFormatWithMultiTsv:
	case CollectionFormatWithMultiPipes:
	case CollectionFormatWithMultiMulti:

	default:
		return nil, fmt.Errorf("unexpected CollectionFormatWithMulti value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *CollectionFormatWithMulti) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := CollectionFormatWithMulti(ii)

	switch v {
	case CollectionFormatWithMultiCsv:
	case CollectionFormatWithMultiSsv:
	case CollectionFormatWithMultiTsv:
	case CollectionFormatWithMultiPipes:
	case CollectionFormatWithMultiMulti:

	default:
		return fmt.Errorf("unexpected CollectionFormatWithMulti value: %v", v)
	}

	*i = v

	return nil
}

// QueryParameterSubSchemaType is an enum type.
type QueryParameterSubSchemaType string

// QueryParameterSubSchemaType values enumeration.
const (
	QueryParameterSubSchemaTypeString = QueryParameterSubSchemaType("string")
	QueryParameterSubSchemaTypeNumber = QueryParameterSubSchemaType("number")
	QueryParameterSubSchemaTypeBoolean = QueryParameterSubSchemaType("boolean")
	QueryParameterSubSchemaTypeInteger = QueryParameterSubSchemaType("integer")
	QueryParameterSubSchemaTypeArray = QueryParameterSubSchemaType("array")
)

// MarshalJSON encodes JSON.
func (i QueryParameterSubSchemaType) MarshalJSON() ([]byte, error) {
	switch i {
	case QueryParameterSubSchemaTypeString:
	case QueryParameterSubSchemaTypeNumber:
	case QueryParameterSubSchemaTypeBoolean:
	case QueryParameterSubSchemaTypeInteger:
	case QueryParameterSubSchemaTypeArray:

	default:
		return nil, fmt.Errorf("unexpected QueryParameterSubSchemaType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *QueryParameterSubSchemaType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := QueryParameterSubSchemaType(ii)

	switch v {
	case QueryParameterSubSchemaTypeString:
	case QueryParameterSubSchemaTypeNumber:
	case QueryParameterSubSchemaTypeBoolean:
	case QueryParameterSubSchemaTypeInteger:
	case QueryParameterSubSchemaTypeArray:

	default:
		return fmt.Errorf("unexpected QueryParameterSubSchemaType value: %v", v)
	}

	*i = v

	return nil
}

// PathParameterSubSchemaType is an enum type.
type PathParameterSubSchemaType string

// PathParameterSubSchemaType values enumeration.
const (
	PathParameterSubSchemaTypeString = PathParameterSubSchemaType("string")
	PathParameterSubSchemaTypeNumber = PathParameterSubSchemaType("number")
	PathParameterSubSchemaTypeBoolean = PathParameterSubSchemaType("boolean")
	PathParameterSubSchemaTypeInteger = PathParameterSubSchemaType("integer")
	PathParameterSubSchemaTypeArray = PathParameterSubSchemaType("array")
)

// MarshalJSON encodes JSON.
func (i PathParameterSubSchemaType) MarshalJSON() ([]byte, error) {
	switch i {
	case PathParameterSubSchemaTypeString:
	case PathParameterSubSchemaTypeNumber:
	case PathParameterSubSchemaTypeBoolean:
	case PathParameterSubSchemaTypeInteger:
	case PathParameterSubSchemaTypeArray:

	default:
		return nil, fmt.Errorf("unexpected PathParameterSubSchemaType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *PathParameterSubSchemaType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := PathParameterSubSchemaType(ii)

	switch v {
	case PathParameterSubSchemaTypeString:
	case PathParameterSubSchemaTypeNumber:
	case PathParameterSubSchemaTypeBoolean:
	case PathParameterSubSchemaTypeInteger:
	case PathParameterSubSchemaTypeArray:

	default:
		return fmt.Errorf("unexpected PathParameterSubSchemaType value: %v", v)
	}

	*i = v

	return nil
}

// HeaderType is an enum type.
type HeaderType string

// HeaderType values enumeration.
const (
	HeaderTypeString = HeaderType("string")
	HeaderTypeNumber = HeaderType("number")
	HeaderTypeInteger = HeaderType("integer")
	HeaderTypeBoolean = HeaderType("boolean")
	HeaderTypeArray = HeaderType("array")
)

// MarshalJSON encodes JSON.
func (i HeaderType) MarshalJSON() ([]byte, error) {
	switch i {
	case HeaderTypeString:
	case HeaderTypeNumber:
	case HeaderTypeInteger:
	case HeaderTypeBoolean:
	case HeaderTypeArray:

	default:
		return nil, fmt.Errorf("unexpected HeaderType value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *HeaderType) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := HeaderType(ii)

	switch v {
	case HeaderTypeString:
	case HeaderTypeNumber:
	case HeaderTypeInteger:
	case HeaderTypeBoolean:
	case HeaderTypeArray:

	default:
		return fmt.Errorf("unexpected HeaderType value: %v", v)
	}

	*i = v

	return nil
}

// APIKeySecurityIn is an enum type.
type APIKeySecurityIn string

// APIKeySecurityIn values enumeration.
const (
	APIKeySecurityInHeader = APIKeySecurityIn("header")
	APIKeySecurityInQuery = APIKeySecurityIn("query")
)

// MarshalJSON encodes JSON.
func (i APIKeySecurityIn) MarshalJSON() ([]byte, error) {
	switch i {
	case APIKeySecurityInHeader:
	case APIKeySecurityInQuery:

	default:
		return nil, fmt.Errorf("unexpected APIKeySecurityIn value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *APIKeySecurityIn) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := APIKeySecurityIn(ii)

	switch v {
	case APIKeySecurityInHeader:
	case APIKeySecurityInQuery:

	default:
		return fmt.Errorf("unexpected APIKeySecurityIn value: %v", v)
	}

	*i = v

	return nil
}

func marshalUnion(maps ...interface{}) ([]byte, error) {
	result := make([]byte, 1, 100)
	result[0] = '{'
	isObject := true

	for _, m := range maps {
		j, err := json.Marshal(m)
		if err != nil {
			return nil, err
		}

		if string(j) == "{}" {
			continue
		}

		if string(j) == "null" {
			continue
		}

		if j[0] != '{' {
			if len(result) == 1 && (isObject || bytes.Equal(result, j)) {
				result = j
				isObject = false

				continue
			}

			return nil, errors.New("failed to union map: object expected, " + string(j) + " received")
		}

		if !isObject {
			return nil, errors.New("failed to union " + string(result) + " and " + string(j))
		}

		if len(result) > 1 {
			result[len(result)-1] = ','
		}

		result = append(result, j[1:]...)
	}

	// Close empty result.
	if isObject && len(result) == 1 {
		result = append(result, '}')
	}

	return result, nil
}
// Regular expressions for pattern properties.
var (
	regexX = regexp.MustCompile("^x-")
	regex = regexp.MustCompile("^/")
	regex093Default = regexp.MustCompile("^([0-9]{3})$|^(default)$")
)
